### ISSUE TITLE
Provide native support for musl clib via prebuild package

### ISSUE THREAD

**Issue by spacewander** [WasmEdge/WasmEdge#1148]
## Motivation

I am going to integrate WasmEdge with APISIX via https://github.com/api7/wasm-nginx-module.

APISIX maintains Alpine Linux image so we need to support musl, both in x64 and in arm64.

At a first glance, it looks like WasmEdge doesn't support musl?

Using glibc-on-alpine is not an option to me, as:
1. it is not official support
2. it doesn't support arm64
3. I tried it before, got some weird issues, and gave up

## Details

It would be great if WasmEdge can have native musl support via prebuild package.
(It doesn't block the APISIX integration though as I can disable it under Alpine Linux)

**Comment by juntao** [comment]
I think we have experimented with musl support. 

I will let @hydai and @O3Ol to chime in here. Thanks.

**Comment by redfave** [comment]
Related issues: #1015 and #1147.

**Comment by spacewander** [comment]
@redfave 
Thanks for your suggestion.

**Comment by jprendes** [comment]
It should be easy to adapt #2699 to build the shared library and the cli tools. The the install script can add support for alpine.

**Comment by hydai** [comment]
If you are going to build WasmEdge on Alpine, it's pretty easy now:

```
apk add cmake ninja clang lld-dev llvm-dev boost-dev musl-dev llvm-static git
export CC=clang
export CXX=clang++
cmake -Bbuildmusl -GNinja -DCMAKE_BUILD_TYPE=Release .
cmake --build buildmusl
```

I would like to know which is the best practice to ship the prebuilt packages on Alpine. For example, Fedora prefers to use dynamically linked libraries. Arch asks us to use the `spdlog-dev` instead of bundled one. Now, we have the statically linked libraries on Alpine by adapting #2699. Do we need to create dynamically linked libraries for it?

**Comment by hydai** [comment]
We already have a build for musl-libc on Alpine after https://github.com/WasmEdge/WasmEdge/pull/2699 merged. Closing this. Please feel free to re-open it if you have any questions.
