### ISSUE TITLE
WasmEdge_HostRegistration_Wasi can't be used with WasmEdge_ExecutorInstantiate

### ISSUE THREAD

**Issue by spacewander** [WasmEdge/WasmEdge#1280]
## Description

As the title. Not sure if it is a bug or by design.

### Current State

When using `WasmEdge_ConfigureAddHostRegistration(ConfCxt, WasmEdge_HostRegistration_Wasi);` to  register Wasi and using `WasmEdge_ExecutorInstantiate` to run the Wasm code, the Wasi is not registered.

Meanwhile, using `WasmEdge_ImportObjectCreateWASI` & `WasmEdge_ExecutorRegisterImport` can solve the problem.

Not sure if `WasmEdge_ConfigureAddHostRegistration(ConfCxt, WasmEdge_HostRegistration_Wasi)` can only be used with `WasmEdge_VMExecute`.

### Expected

 `WasmEdge_ConfigureAddHostRegistration(ConfCxt, WasmEdge_HostRegistration_Wasi);` works the same as  `WasmEdge_ImportObjectCreateWASI` & `WasmEdge_ExecutorRegisterImport` 

## Environment

- Hardware Architecture: (e.g. x86\_64 or aarch64) x86\_64
- Operating system: (e.g. Ubuntu 20.04 or CentOS 7.6) Ubuntu 20.04

The following information is optional. Please provide them only if you have built from source.
- C++ Compiler version:
- CMake version:
- CMake flags: (e.g. `-DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_AOT_RUNTIME=ON`)
- Boost version:

**Comment by hydai** [comment]
This is expected as design decision.

The `HostRegistration` in `Configure` will only apply to the VM instance. Because it will take care about the whole processes in the whole VM flow. If users want to use the loader and executor directly, then they should compose the details by themselves.

This is also described in the C API docs: https://github.com/WasmEdge/WasmEdge/blob/master/docs/book/en/src/embed/c/ref.md#configurations
