### ISSUE TITLE
Provide a wasm-compatible Rust TLS implementation

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#1430]
## Motivation

The WasmEdge networking socket API provides support for TCP and HTTP connections. But many web services today require HTTPS connections. That means we need to support TLS in WasmEdge. The [Rustls](https://github.com/rustls/rustls) crate is the most popular TLS implementation in Rust. However, Rustls is based on the Ring library, which cannot be compiled into WebAssembly.

In WasmEdge, we now [support](https://github.com/WasmEdge/WasmEdge/issues/345) the [wasi-crypto spec](https://github.com/WebAssembly/wasi-crypto). That allows us to compile the [rust-crypto](https://crates.io/crates/crypto) library into WebAssembly and run on WasmEdge. The goal of this project is to create a Rust TLS implementation based on rust-crypto.

## Specification

1. Review and understand the Rustls crate and its use.
2. Review wasi-crypto and the Rust API from rust-crypto.
3. Implement the TLS spec similar to Rustls using wasi-crypto.
4. Implement HTTPS support in WasmEdge based on the new TLS library.

## Qualifications

To apply this LFX mentorship, there are some minimum qualifications:

1. Experience with the Rust programming language.
2. Experience with the WebAssembly spec.
3. Familiarity with crypto algos.

## Appendix

1. wasi-crypto: https://github.com/WebAssembly/wasi-crypto
2. Rustls: https://github.com/rustls/rustls
3. rust-crypto: https://crates.io/crates/crypto
4. WasmEdge socket API: https://github.com/second-state/wasmedge_wasi_socket
5. WasmEdge HTTP examples: https://wasmedge.org/book/en/dev/rust/networking-nonblocking.html

**Comment by sonder-joker** [comment]
Some additional relative information.

**Comment by TieWay59** [comment]
Hello, I feel the third stage, Implementing the TLS Spec, is a huge milestone, and I'd like to begin by reviewing the rustls APIs. To take on this topic, one should get to know both rust-crypto and the TLS spec well.
I'm a SE student who hasn't previously concentrated on the TLS protocol. Any advise on how to become more familiar with this task quickly would be greatly appreciated.😀

**Comment by juntao** [comment]
@TieWay59 I think one way to do is to fork the Rustls library, find out how Ring is used and swap Ring API calls for Rust Crypto. 😃

**Comment by sonder-joker** [comment]
Here are some of my insights
## Adapt rustls rather than reimplement tls.
TLS protocol is very huge. Reimplementation not only means a lot of work, but also may lack of security. Reuse rustls consider more better. 

## What is problem in rustls
Rustls highly coupled with Ring. However, many users of rustls want to replace Ring, which mean provide a crypto layer. https://github.com/rustls/rustls/issues/521 talk about it.

## Which crypto layer to choose?
May [RustCrypto](https://github.com/RustCrypto/traits) as a middle layer is good. However, it depends on the upstream.

## So what we need to do
Abstract a set of cryptographic apis (I hope it's RustCrypto) in Rustls and pull request it upstream, so that upstream can use conditional compilation (provide an option like `feature = "wasi-crypto"`) to choose the encryption backend. Then we provide  an Wasi-crypto implementation. So rustls can change from `Rustls -> Ring` to `Rustls -> RustCrypto -> Wasi-crypto`.

## Main problem
The APIs of ring and rust-crypto and wasi-crypto are very different. For rustls, it fully coupled to ring, It also depend on [webpki](https://github.com/briansmith/webpki), we also need to adapt it. For wasi-crypto and rust-crypto, design is very different. Rust-crypto assume you owned resource, but wasi-crypto only let you get resource. We probably also need to pull request RustCrypto.

**Comment by TieWay59** [comment]
Thank you @juntao & @sonder-joker, after simply going through the rustls code base, I agree that TLS protocol is too huge to reimplementation. I‘ll keep investigate into the code base of [RustCrypto](https://github.com/RustCrypto/traits) , [rust-crypto](https://crates.io/crates/crypto) and [wasi-crypto spec](https://github.com/WebAssembly/wasi-crypto) to find more inspiration.

**Comment by sonder-joker** [comment]
For those who want to start working here, you can start by abstract traits that coupled with ring and webpki (for ring/webpki relative use `feature = "ring" ` and `#[config(ring)]` or other, any idea you like). You can also compare your design with [rust-crypto](https://github.com/RustCrypto/traits).

**Comment by TieWay59** [comment]
Hi @sonder-joker, here is my progress:

Since rustls have lots of dependence on the ring crate, I investigate all related lines to evaluate the scale of re-implementation and listed them in a table. It's a very verbose result so I keep it in my blog post. (see https://www.yuque.com/tieway59/xopdgg/zmkx5g)

> you can start by abstract traits

As per my investigation, there are more structs than traits that need to be replaced. May I ask for further information about "abstract traits", I'm still not clear about it. Do you mean I should first focus on the trait provided by the ring crate?

**Comment by juntao** [comment]
Hi @TieWay59 

I think the idea was to create new layer of abstract API interface (traits) between Ring and Rustls. This way, we can use Ring and Rust Crypto to implement the same API.

However, I also think this is perhaps more work than we can do. I think it is probably a good idea to provide WASI-crypto implementations of the same Rust API Ring provides to Rustls. That requires us to fork Rustls. That's what you want to do, right? Thanks.

**Comment by TieWay59** [comment]
Thank you @juntao 

> That requires us to fork Rustls. That's what you want to do, right?

Sorry for my late reply, and yes that's what I tend to build for this task. I wonder if it's reasonable to maintain a fork of Rustls in which we would replace all the Ring API with WASI-crypto implementations?

IMHO, When the upstream Rustls updates, it will be difficult to merge incoming updates. Is it acceptable? What do you think of the practice?

Thanks.

**Comment by rektide** [comment]
> The [Rustls](https://github.com/rustls/rustls) crate is the most popular TLS implementation in Rust. However, Rustls is based on the Ring library, which cannot be compiled into WebAssembly.

why is this true?

**Comment by juntao** [comment]
@rektide I would love to see Ring get compiled into wASM. But the issue have been under discussion for 3 years. Do you have insights in its latest development? Thanks!

**Comment by ipuustin** [comment]
Would be great to see this reviewed: https://github.com/briansmith/ring/pull/1568

**Comment by jedisct1** [comment]
Ring has been ported to wasm: https://github.com/jedisct1/ring-wasi

But I'd really recommend using [BoringSSL](https://github.com/jedisct1/boringssl-wasm) instead. It has excellent bindings for Rust.

Or implement a new set of host functions specifically to perform HTTP queries. Maybe a safe, minimal subset of `libcurl`?

**Comment by hydai** [comment]
Hi @jedisct1 
Thanks for the information.
The current implementation of wasi-crypto in WasmEdge uses OpenSSL. Do you mean using BoringSSL to replace it? Or create a new extension based on BoringSSL, said, `wasm-boringssl` for this?

**Comment by GavBog** [comment]
https://github.com/briansmith/ring/issues/918#issuecomment-1748084678

**Comment by hydai** [comment]
Hi @juntao and @L-jasmine 
I think this issue is resolved due to the rustls can be compiled into wasm directly. Closing it.

**Comment by guest271314** [comment]
> Ring has been ported to wasm: https://github.com/jedisct1/ring-wasi
> 
> But I'd really recommend using [BoringSSL](https://github.com/jedisct1/boringssl-wasm) instead. It has excellent bindings for Rust.
> 
> Or implement a new set of host functions specifically to perform HTTP queries. Maybe a safe, minimal subset of `libcurl`?

How would I go about using BoringSSL (https://github.com/jedisct1/boringssl-wasm) to implement TLS in WASM in the browser?
