### ISSUE TITLE
can not find liblldCore.a

### ISSUE THREAD

**Issue by calvin2021y** [WasmEdge/WasmEdge#1575]
## Description

since LLVM 1400, there is no lldCore, lldDriver, lldReaderWriter, lldYAML

should replace with `lldMinGW lldCOFF lldMachO lldWasm`

**Comment by hydai** [comment]
Hi @calvin2021y 
May I ask what's your environment and compilation flags/options?

**Comment by calvin2021y** [comment]
I has one question for AOT, do I need liblld*.a for android host binary?  

I mean generate aot binary for android from linux,  run by android app without link to liblld*.a.   (I wnat to avoid build liblld*.a for android target)

**Comment by hydai** [comment]
The answer is no. If you don't need to run AOT(wasmedgec) on the android platform, then set `WASMEDGE_BUILD_AOT_RUNTIME` to `OFF`. The runner(wasmedge) can still run the generated aot binary which may be compiled in the other place. Please make sure the base os and hardware architecture are the same.

**Comment by calvin2021y** [comment]
I need AOT on android.

I can generate aot from aarch64, then run from android and IOS (event I build library for android with set WASMEDGE_BUILD_AOT_RUNTIME=OFF)? 

Is this case the AOT is ignored and just use the wasm format?

**Comment by hydai** [comment]
Yup. Set `WASMEDGE_BUILD_AOT_RUNTIME=OFF` will not generate `wasmedgec` and its related libraries only.
You can still use `wasmedge` to load and execute wasm format and aot binary. Because the aot binary-only contains its origin wasm file and the native binary. There are no llvm-related dependencies inside the aot file.
