### ISSUE TITLE
Evangelising WASMEdge Community in India 

### ISSUE THREAD

**Issue by shivaylamba** [WasmEdge/WasmEdge#1625]
## Motivation

The Indian developer space specially the student developer communities is huge. So it makes sense to introduce modern technologies like WebAssembly in order to help make students/young developers keep upto speed specially with cloud native technologies. 

## Some stats: 
- Indians represent the highest participation in programs like Google Summer of Code, Linux Foundation Mentorship programs
- More than 100K students graduate every year 

## Scope/Opportunity: 
- Recent initiatives like https://community.cncf.io/cloud-native-students/ has seen a huge rise in popularity of DevOps, Cloud Native technologies within Indian students/young developer community. And introducing concepts like Web Assembly and WASMEdge is the next logical step to help them get into the journey of serverless, containers and WebAssembly. 

## What can we do?
- Conduct workshops/sessions on Web Assembly, WASMEdge in colleges/ student developer clubs. 
- Collaborate with initiatives like the Cloud Native Students to conduct sessions, generate materials like videos/blogs to further evangelise WASMEdge
- Swag distribution during these sessions
- Conduct live hands on workshops on how to contribute to WASMEdge. 
- Have WASMEdge participate in hackathons, other types of developer focused contests

## Outcomes
- See more interest/participation of students/ young developers in initiatives like LFX Mentorship/Google Summer of Code/Internships for WASMEdge
- More contributions coming from the community 
- Some new content such as blogs

**Comment by shivaylamba** [comment]
cc @mritunjaysharma394

**Comment by mritunjaysharma394** [comment]
+ 1 to what @shivaylamba has proposed, it has huge potential and can really create ripple effects in India and we can help contributing to this great cause!

**Comment by juntao** [comment]
cc @SAtacker

**Comment by SAtacker** [comment]
Yes, I too agree with all these points by @shivaylamba and @mritunjaysharma394 . Once WASM and Wasmedge becomes familiar to everyone i.e. there are some introductory courses on it which are available for all and its use is thoroughly understood by the majority of people, contributions will surely flood in.
YouTube channels are usually a very good source of learning and promoting educational content.
In short, until WASM is not a familiar concept to everyone, there's just waiting. 
As far as the core functioning of Wasmedge is concerned, I can't speak for that as I haven't done anything yet myself.
We all appreciate the efforts that Shivay and Mritunjay are putting into making everyone's understanding better. This is definitely going to help getting people onboard. There's lots of thought they have put into it, I am a bit busy until August due to GSoC but I am there for as much as I can until then. Appreciate this.
Thanks

**Comment by dannypsnl** [comment]
Please move to discussion.
