### ISSUE TITLE
[CLI tool] Should command mode takes the WASI exit code as the return value?

### ISSUE THREAD

**Issue by Zhangyx24** [WasmEdge/WasmEdge#1706]
## Steps to reproduce

The wat file :
(module
  (type (;0;) (func (result f64)))
  (func (;0;) (type 0) (result f64)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.div
    f64.copysign)
  (export "_start" (func 0)))

`wat2wasm main.wat`
`wasm3 main.wasm`

## Expected result
0
and wasmtime execute this and print 0.

## Actual result
print nothing

## version
wasmedge 0.9.1
ubuntu20.04 or macOS

**Comment by hydai** [comment]
Hi @Zhangyx24 
Thanks for reporting this. According to my tests, I found that if this is not a `_start` function, then the result is the same. However, once the name is `_start` function, then there is nothing to print.

<img width="1792" alt="截圖 2022-08-01 at 22 00 17@2x" src="https://user-images.githubusercontent.com/2776756/182164967-f98891ef-a898-4ca3-a50f-c189f444966a.png">


And this result is caused by this section: https://github.com/WasmEdge/WasmEdge/blob/master/lib/driver/tool.cpp#L241-L254

We take the WASI exit code as the return value when users want to call a function named `_start`. Maybe this is the wrong design. I will discuss it with my team member and get back to you.

For example, using command mode to execute will receive nothing. However, using the same wasm file with reactor mode will receive `-0`.

<img width="1792" alt="截圖 2022-08-01 at 22 10 24@2x" src="https://user-images.githubusercontent.com/2776756/182166911-e9d031fb-487c-4849-9099-fc448637eeb6.png">

**Comment by Zhangyx24** [comment]
Thank you very much for your answer and patience.

**Comment by hydai** [comment]
These reported bugs mean a lot to us. Thank you again. We will get these fixed ASAP.
