### ISSUE TITLE
Running twice ?

### ISSUE THREAD

**Issue by Zhangyx24** [WasmEdge/WasmEdge#1718]
## Description
[test-c.txt](https://github.com/WasmEdge/WasmEdge/files/9242354/test-c.txt)
[test-wat.txt](https://github.com/WasmEdge/WasmEdge/files/9242362/test-wat.txt)

Using the test.c to execute the `main` function in the test.wasm.
The test.c is uploaded as test-c.txt and the test.wat is uploaded as test-wat.txt.

### Steps to reproduce
`wat2wasm test.wat`
`gcc -o test test.c -lwasmedge_c`
`./test`

### Expected result
Print the following:
"Print_input_host 6513249"

### Actual result
Print it twice,as the following shows:
"Print_input_host 6513249
Print_input_host 6513249"

## Environment
- Hardware Architecture: ( x86\_64 )
- Operating system: ( Ubuntu 20.04 )
- wasmedge : 0.9.1

**Comment by q82419** [comment]
Hi @Zhangyx24 ,

According to your WAT:

```
(module
  (import "env" "print_input" (func $print_input (param i32)))

  (memory 1)
  (data 0 (offset (i32.const 0)) "abc")
  (data 0 (offset (i32.const 100)) "hello")
  (data 0 (offset (i32.const 1000)) "Good morning !")
  (data 0 (offset (i32.const 2400)) "123")

  (start $main)
  (func $main (export "main")
    (call $print_input (i32.load offset=0 (i32.const 0)))
  )
)
```

This WASM file has the start section `(start $main)`.
The [instantiation steps in WASM spec](https://webassembly.github.io/spec/core/exec/modules.html#instantiation) says:
```
16. If the start function is not empty, then:
   a. Let start be the start function module.start.
   b. Execute the instruction call start.func .
```

So when instantiating this WASM, the `main` will be executed because it's assigned as the start function.
When you call the `WasmEdge_VMRunWasmFromFile` in C code, this API will load, validate, and instantiate the WASM module first, and then invoke the function by name (which is assigned as `WasmEdge_StringCreateByCString("main")`).
Therefore the `main` function is executed twice.

Thanks.

**Comment by Zhangyx24** [comment]
Thanks four your answer!
