### ISSUE TITLE
[CI] Add CI tests for httpreq plugin

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1763]
## Motivation

CI test is essential for software. So we need to add CI tests for httpreq plugin

## Appendix

example: https://github.com/WasmEdge/WasmEdge/blob/master/.github/workflows/build-extensions.yml

**Comment by hydai** [comment]
Hi @2019zhou 
I found some issues that I didn't identify in the previous review:

1. All of the pointers should be checked whether it's nullptr or not before use: https://github.com/WasmEdge/WasmEdge/blob/master/plugins/httpsreq/httpsreqfunc.cpp#L32
2. You should return the `error code` in the return value instead of using `exit`. Because the `exit` will terminate the whole program, it will make the wasmedge exit without any other error handling: https://github.com/WasmEdge/WasmEdge/blob/master/plugins/httpsreq/httpsreqfunc.cpp#L49
3. Same as `abort`: https://github.com/WasmEdge/WasmEdge/blob/master/plugins/httpsreq/httpsreqfunc.cpp#L73

**Comment by 2019zhou** [comment]
OK
