### ISSUE TITLE
Need wasmedge c api sample: use image data as parameter to call wasm function

### ISSUE THREAD

**Issue by chairwa** [WasmEdge/WasmEdge#1772]
This is c api:
https://wasmedge.org/book/en/embed/c/ref.html

I didnot see such a c api sample as the following js sample which use image ByteArray as parameter:
https://github.com/second-state/wasm-learning/tree/master/faas/tflite_ssd

or take the following as example:
https://github.com/second-state/wasm-learning/blob/master/android/test.c
In that example, birds_v1.wasm is built from main.rs and receive image file path as argument. 
If birds_v1.wasm were changed to lib.rs function and use [u8] image data as parameter,
how to change test.c accordingly?

**Comment by q82419** [comment]
Hi,

This is done by the nodejs addon.
For the pure WASM, only scalar types (int32, int64, float32, float64, v128) accepted for function parameters and returns.
The WASM file you mentioned in the example is generated by the wasm-bindgen so that can support the ByteArray passing.
To handle the wasm-bindgen generated WASM, please refer to the [napi](https://github.com/second-state/ssvm-napi).

**Comment by dannypsnl** [comment]
Please move to discussion.
