### ISSUE TITLE
wasmedge CLI - AOT Compiler does not work itself on pure windows, terminal.

### ISSUE THREAD

**Issue by ilsubyeega** [WasmEdge/WasmEdge#1898]
## Description
Compiling 
### Current State

As from `Steps to Reproduce`, i could not use aot compiler from wasmedge cli with pure terminal (launching via `start cmd`)
However, It was possible to use AOT compiler with `x64 Native Tools Command Prompt for VS 2022`. See https://github.com/WasmEdge/WasmEdge/issues/953#issuecomment-1049387972.
### Expected
It should be not throws the error, and builds correctly.

## Environment
Windows OS Build of sandboxed version: 22621.730
WasmEdge version: 0.11.1
- Hardware Architecture: (e.g. x86\_64 or aarch64): x64
- Operating system: (e.g. Ubuntu 20.04 or CentOS 7.6): Windows 11

+) ive tested this with powershell and cmd both, but failed.
## Steps to Reproduce
1. Create Windows sandbox
2. Install rustlang by rustup-init (installed with visual studio option)
3. Install wasmedge from github releases (the windows sandbox seems to not includes the winget feature, so manually installs it.)
4. Run command `rustup target add wasm32-wasi`
5. download code from https://github.com/ilsubyeega/wasmedge-playground/tree/main/functions/rs-simple-function-aot
6. run `cargo build --target wasm32-wasi` (run successfully)
7. run `wasmedgec target/wasm32-wasi/debug/rs_simple_function.wasm target/aot.wasm`
8. Gets the error log.
```
PS C:\Users\WDAGUtilityAccount\Desktop\wasmedge-playground-main\functions\rs-simple-function> wasmedgec target/wasm32-wasi/debug/rs_simple_function.wasm target/aot.wasm
[2022-10-04 17:07:55.246] [info] compile start
[2022-10-04 17:07:55.284] [info] verify start
[2022-10-04 17:07:55.293] [info] optimize start
[2022-10-04 17:07:56.138] [info] codegen start
[2022-10-04 17:07:56.772] [info] output start
lld-link: error: could not open 'libcmt.lib': no such file or directory
[2022-10-04 17:07:56.782] [error] link error
[2022-10-04 17:07:56.785] [info] output start
```
9. launch `x64 Native Tools Command Prompt for VS 2022`
10. do the same of number 7.
11. run `wasmedge --reactor target/aot.wasm add 3 3`
12. it logs `6`.
![image of each log of pure terminal and vs terminal](https://user-images.githubusercontent.com/37479424/193770779-de1acd1f-c44b-4e60-8737-02c8bb82d38b.png)

### Alternative way
1. Do the ~4 steps from above.
2. Download https://github.com/WasmEdge/WasmEdge/raw/master/examples/wasm/fibonacci.wasm
3. run `wasmedgec fibonacci.wasm aot.wasm` from each terminal(pure one and vs2022 one)
4. Find out that pure one didnt built successfully, but vs2022 does)
![image of each log of pure terminal and vs terminal](https://user-images.githubusercontent.com/37479424/193771463-45dd2bf1-c2bf-47b3-9ba2-89f38ba4d790.png)

**Comment by hydai** [comment]
Hi @ilsubyeega 
Thanks for raising this issue.
Seems like the VS Prompt added more LIBPATH. I would like to know what is the development environment on the Windows platform. For example, the PowerShell, the CMD, or the Command Prompt for VS? Because I am not a native user on such a platform, it will be helpful if you can give me a hint.

To test this issue, I think the CI workflow will also need to enable various development environments.

**Comment by hydai** [comment]
Hi @ilsubyeega 
Thanks for raising this issue. However, at the current stage, we still have to rely on the `libcmt.lib` to execute the AOT compiled wasm, so the VS prompt environment is still needed.
I am closing this because supporting the AOT compiled wasm on the pure Windows terminal is no longer on our roadmap. I am sorry for the inconvenience.
