### ISSUE TITLE
[Windows] WASI Host function - `open`

### ISSUE THREAD

**Issue by abhinandanudupa** [WasmEdge/WasmEdge#1919]

**Comment by Berrysoft** [comment]
https://github.com/WasmEdge/WasmEdge/blob/b16d9d3e80b84e17974a911c2de94887194ada58/lib/host/wasi/inode-win.cpp#L493-L495

* `CreateFileA` uses current code page, which may not be UTF-8. At least Rust APIs is passing UTF8 path directly to C APIs. The strings should be converted to UTF-16 and passed to `CreateFileW`.
* When preopening directories for WASI, `INode::open` is also used. `FILE_FLAG_BACKUP_SEMANTICS` should be passed to `dwFlagsAndAttributes` to open the directory. See the documentation [here](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilew).

**Comment by Berrysoft** [comment]
I haven't successfully built WasmEdge on Windows, and I don't use it currently neither. It's just a bug I found when trying it. The fix seems not that easy, and it's up to you all to fix it:)

And by the way, it is a hard time to map a Windows path to WASI with WasmEdge, because the colon after the drive letter will be separated here:

https://github.com/WasmEdge/WasmEdge/blob/e8cf55f25eb88fa9eebbdb5e191d036dbc5982d4/lib/host/wasi/environ.cpp#L59

Luckily, UNC path works...
