### ISSUE TITLE
WASI: Make poll_oneoff edge triggered.

### ISSUE THREAD

**Issue by MediosZ** [WasmEdge/WasmEdge#1974]
## Motivation
`poll_oneoff` is using level-triggered mode with epoll in linux. However, applications like tokio assume that ~poll~ works in edge-triggered mode, making them constantly running under WasmEdge.
So using edge-triggered mode is necessary for tokio-based async applications.
Though this is a design problem of WASI, I suppose we use edge-triggered mode by default, and add a option to turn it off if needed.

## Details
Since we use epoll, it's possible to use edge-triggered mode easily.
But `poll_oneoff` is stateless by default, so we need to maintain a epoll descriptor for all incoming pollings. Also the state of these queries should be maintained.

**Comment by MediosZ** [comment]
Implementation details can be found in #1975

**Comment by juntao** [comment]
Can you describe / document the flag needed for the old level-triggered behavior? Thanks.

**Comment by MediosZ** [comment]
We can add an option like `--trigger_mode [ level / edge ]`

**Comment by hydai** [comment]
Since this feature will change the spec of `poll_oneoff`, which means it may break the expected behavior of the `poll_oneoff` function. What's the intention of using the same function name here?
And is it possible to have both `level-trigger` and `edge-trigger` functions in the same wasm application?

**Comment by MediosZ** [comment]
`wasmedge_wasi_socket` and other dependent crates use `poll_oneoff`, so I just change the behavior of the existed function. 
I think we can have two functions, like `poll_oneoff` and `poll_oneoff_et` to provide new behavior without breaking the current one.
But `poll_oneoff_et` is not part of the wasi spec, is that ok?
> And is it possible to have both level-trigger and edge-trigger functions in the same wasm application?
I think it is possible

**Comment by hydai** [comment]
Because both the `level-trigger` and `edge-trigger` functions are available in the same wasm application, it's not really good to use the config/option to change the behavior.

I would like to have `poll_oneoff_e` or `epoll_oneoff` here. Since our WASI-Socket extension is also not part of the WASI spec, it should be fine.

**Comment by MediosZ** [comment]
yeah,I agree with the idea of having both functions, and it would easy to add one option in wasmedge_wasi_socket
