### ISSUE TITLE
Module Linking - add wasm to wasm support to wasmedge-bindgen

### ISSUE THREAD

**Issue by dm4** [WasmEdge/WasmEdge#1981]
## Motivation

In #1877 mentioned we'd like to use some serialize/deserialize protocol to replace interface type. Here we want to use wasmedge-bindgen to achieve this.

## Details

Current wasmedge-bindgen could only work when using rust to call export function from wasm. We'd like to add wasm to wasm support to wasmedge-bindgen.

We might need:
- [ ] Handle extern blocks in rust to generate import functions in wasm
- [ ] Convert function signatures for import functions
- [ ] Allocate/deallocate memory before/after calling wasm

**Comment by dannypsnl** [comment]
### Can GC proposal help?

After more research on the GC proposal, I found that the GC proposal cannot solve exchanging problem directly, though the proposal adds `table.grow` that can increase memory which can make exchanging buffers more convenient. The problem still is compiler has no idea it should rely on these concepts to build its output.

### How to share memory in WASM?

And after deeper research about how to share memory, I found a wasm module can require a buffer first, like `static` bytes in **Rust**. The idea is written in https://wasmbyexample.dev/examples/webassembly-linear-memory/webassembly-linear-memory.rust.en-us.html points out it’s possible to operate exported memory from host/runtime. **wit-bindgen** also uses the same technology to generate shared memory.

The biggest trouble of the solution is, variant-length data is the most interests data here to exchange, like **string**. Since `static` memory will not grow, this is not the solution we are looking for, and the exchanging buffer requires a very complicated protocol to do so.

### Host function to rescue

The newest idea proposed when I'm discussing with @dm4, if host(runtime) can already pass **string** and get **string** from a wasm function, why not a host function exactly doing this for wasm modules?

The prototype of the host function was
```hs
forward-call :: String -> String -> ArgList -> Any
forward-call module-name function-name argument-list = ...
```

Then runtime handles the rest of exchanging issues, this is the next direction we will do experimental.

#### Details

- [ ] implement host function `forward-call`
- [ ] call host function in wasm module written in **Rust**
- [ ] check the exchanged data

**Comment by dannypsnl** [comment]
### 2022/11/23 update

`forward-call` can be say done to the best spot we can get with current technology, to improve the `JSON -> JSON` situation, we need

1. auto convert compound type(e.g. structure) to wasm multi-value
2. able to mark type need memory operation(not every type needs it)

**Comment by hydai** [comment]
Since our focus is moving to CM, do we still need this feature? cc @dm4 @dannypsnl

**Comment by dm4** [comment]
Yes, I think we can close this issue after deciding to move to the component model.
