### ISSUE TITLE
[Help] How to open the debug log?

### ISSUE THREAD

**Issue by 2019zhou** [WasmEdge/WasmEdge#2065]
How to open the debug log of the function?

**Comment by alabulei1** [comment]
@hydai Please help take a look. @2019zhou  wants to open the debug log for HTTPS plugin

**Comment by hydai** [comment]
What kind of debug log do you need?
If you are using libwasmedge, please refer to this function to enable the debug log level: https://github.com/WasmEdge/WasmEdge/blob/master/include/api/wasmedge/wasmedge.h#L240

Otherwise, you have to modify the wasmedge toolchain and call this function instead: https://github.com/WasmEdge/WasmEdge/blob/master/include/common/log.h#L25

**Comment by 2019zhou** [comment]
Thank you.
