### ISSUE TITLE
Missing conversion from `sys::Executor` to `sdk::Executor`

### ISSUE THREAD

**Issue by dannypsnl** [WasmEdge/WasmEdge#2075]
## Motivation
When accessing the host environment in **host function**, @dm4 and I found we need to use `sdk::Engine` to invoke a function across the wasm module, but `sys::Executor` didn't implement the `sdk::Engine` since it's not the type in the same crate. This is correct, and then we have `sdk::Executor` wrapping the `sys::Executor`. However, one cannot get `sdk::Executor` from `sys::Executor`.

## Details

The simplest idea I have is implementing `From<sys::Executor> for sdk::Executor` in the bindings module.

Related to #1981 

## Appendix

Draft code

```rust
impl From <sys::Executor> for Executor {
    pub fn from(value: sys::Executor) -> Self {
        Executor{ inner: value }
    }
}
```

**Comment by dannypsnl** [comment]
The fixing PR merged

**Comment by apepkuss** [comment]
Hi @dannypsnl,

Sorry, I missed this issue. I noticed that the fix has been merged into the master branch, but I still have interest in the issue and the fix. Could you please share the code of using the conversion? Thanks a lot!

**Comment by dannypsnl** [comment]
At https://github.com/second-state/module-interaction-example/blob/main/forward-call/host/src/main.rs#L47-L53

```rust
let mut executor: wasmedge_sdk::Executor = caller.executor_mut().unwrap().into();
let result = target_fn
    .call(
        &mut executor,
        vec![WasmValue::from_i32(final_addr as i32), input[5]],
    )
    .unwrap();
```

Since `call(sdk::Executor, Vec<WasmValue>)` but `caller.executor_mut()` gives `sys::Executor`.

**Comment by apepkuss** [comment]
> At https://github.com/second-state/module-interaction-example/blob/main/forward-call/host/src/main.rs#L47-L53
> 
> ```rust
> let mut executor: wasmedge_sdk::Executor = caller.executor_mut().unwrap().into();
> let result = target_fn
>     .call(
>         &mut executor,
>         vec![WasmValue::from_i32(final_addr as i32), input[5]],
>     )
>     .unwrap();
> ```
> 
> Since `call(sdk::Executor, Vec<WasmValue>)` but `caller.executor_mut()` gives `sys::Executor`.

@dannypsnl Thanks for the reply. I checked the code by following the link you provided and found that the type of `caller` is `wasmedge_sys::CallingFrame`. In the case of the example, the correct way is to (1) create a [`wasmedge_sdk::Caller`](https://wasmedge.github.io/WasmEdge/wasmedge_sdk/struct.Caller.html) instance by using the [`wasmedge_sdk::Caller::new`](https://wasmedge.github.io/WasmEdge/wasmedge_sdk/struct.Caller.html#method.new) method; (2) then you can use the `Caller` instance to obtain the relevant `Executor`, `Instance` and `Memory` via the [APIs](https://wasmedge.github.io/WasmEdge/wasmedge_sdk/struct.Caller.html#method.executor).

In addition, the `From` trait provides another choice to "create" a high-level `sdk::Executor` from a low-level `sys::Executor`, but it is an "inappropriate" way to get a high-level instance, as it works in this case, but it also can be used in other irrelevant cases. It should be guaranteed that all users follow the correct way to do things without side effects. So please use the `sys::CallingFrame` instance to create a `sdk::Caller` instance via the API `Caller::new` first, then obtain the `sdk::Executor`.

Sorry for the late explanation!

**Comment by dannypsnl** [comment]
For me, it's more like `executor_mut` leak the low-level abstraction, maybe returns `sdk::Executor` is possible here?

**Comment by dannypsnl** [comment]
@apepkuss I guess the most confusing place is I can have
```rust
#[host_function]
fn xxx(_: Caller, ...) { ... }
```
but not
```rust
with_func::<...>(
  "xxx",
  move |_: Caller, ...| { ... },
  None
)
```

**Comment by apepkuss** [comment]
> @apepkuss I guess the most confusing place is I can have
> 
> ```rust
> #[host_function]
> fn xxx(_: Caller, ...) { ... }
> ```
> 
> but not
> 
> ```rust
> with_func::<...>(
>   "xxx",
>   move |_: Caller, ...| { ... },
>   None
> )
> ```
> 
> By the way, I already [update the code](https://github.com/second-state/module-interaction-example/commit/dfb53cd0841892b5e6026bf13c82146929960949).

You got the point! The `#[host_function]` macro will expand before compiling the code, and it will "rewrite" the function like this:

```rust
fn xxx(frame: CallingFrame, ...) {
    let caller = Caller::new(frame);
    ...
}
```
As you can see, we use the proc-macro to "hide" the type conversion so that users can focus on the high-level type `Caller` instead of the low-level type `CallingFrame`. In addition, we cannot introduce a more elegant design here as the argument of the `CallingFrame` type is given by the low-level WasmEdge Runtime at runtime instead of by users before the compilation. The low-level runtime only recognizes "CallingFrame", therefore, when users use a closure to declare a host function, then the proc-macro cannot be used in such a case, they have to convert the argument of "CallingFrame" type to a variable of "Caller" type by themselves.

Hope the explanation above can help you understand the design, and answer your question. Thanks a lot!

**Comment by apepkuss** [comment]
> @apepkuss I guess the most confusing place is I can have
> 
> ```rust
> #[host_function]
> fn xxx(_: Caller, ...) { ... }
> ```
> 
> but not
> 
> ```rust
> with_func::<...>(
>   "xxx",
>   move |_: Caller, ...| { ... },
>   None
> )
> ```
> 
> By the way, I already [update the code](https://github.com/second-state/module-interaction-example/commit/dfb53cd0841892b5e6026bf13c82146929960949).

As for the updated code, I strongly recommend creating a `Caller` variable with the argument `frame` at the very beginning of the closure, so that all of the rest code of the closure uses the high-level objects, like memory and executor. In your updated code, due to the Caller declared [here](https://github.com/second-state/module-interaction-example/blob/dfb53cd0841892b5e6026bf13c82146929960949/forward-call/host/src/main.rs#L47), the memory variable used before is still of low-level type.

**Comment by dannypsnl** [comment]
Ok, then I guess the issue can close?

**Comment by apepkuss** [comment]
Sure. I'll close it. Thanks!
