### ISSUE TITLE
[WASI-NN] PyTorch backend doesn't support GPU version

### ISSUE THREAD

**Issue by shenben** [WasmEdge/WasmEdge#2140]
### Current State

WasmEdge only supports :libtorch-1.8.0~1.8.2-cpu.

WasmEdge does not support :
* libtorch-1.7.1-cpu 
* libtorch-1.9.0-cpu 
* libtorch-1.7.1~1.9.0-cuda

In summary,  WasmEdge does not support pytorch operations on GPU, only on CPU.

### Expected

WasmEdge both supports pytorch operations on CPU and  <font color='red'>**on GPU**</font>.

## Environment

- Hardware Architecture: x86_64
 
- Operating system:  Ubuntu 22.04.1 LTS

- NVIDIA-SMI：   Driver Version: 450.203.03   CUDA Version: 11.0 

- C++ Compiler version:  g++ 11.3.0

- Boost version:1.74.0

- wasmedge version: 0.11.2

## Steps to Reproduce

*WasmEdge runs pytorch task smooth on CPU but can not on GPU.*

load libtorch-one_version-cpu:
```
$ export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/user/libtorch-1.8.0-cpu/lib
# or
# export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/user/libtorch-1.8.1-cpu/lib
# or
# export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/user/libtorch-1.8.2-cpu/lib
```

then WasmEdge runs pytorch task:
```
$ cd ~/wasmedge-example/pytorch/
$ wasmedge --dir .:. out.wasm mobilenet.pt input.jpg
```

the task can smoothly run:
```
Read torchscript binaries, size in bytes: 14376860
Loaded graph into wasi-nn with ID: 0
Created wasi-nn execution context with ID: 0
Read input tensor, size in bytes: 602112
[W NNPACK.cpp:80] Could not initialize NNPACK! Reason: Unsupported hardware.
Executed graph inference
   1.) [954](20.6681)banana
   2.) [940](12.1483)spaghetti squash
   3.) [951](11.5748)lemon
   4.) [950](10.4899)orange
```

```
$ export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/user/libtorch-1.8.1-cuda/lib
# any versions of cuda-based libtorch can not support the same pytorch task.
# export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/user/libtorch-1.9.0-cpu/lib
# # other versions of cpu-based libtorch can not support the same pytorch task.
```

then WasmEdge runs the same pytorch task after setting different version libtorch or cuda-based libtorch:
```
$ cd ~/wasmedge-example/pytorch/
$ wasmedge --dir .:. out.wasm mobilenet.pt input.jpg
```

the task got error:
```
Read torchscript binaries, size in bytes: 14376860
Loaded graph into wasi-nn with ID: 0
Created wasi-nn execution context with ID: 0
Read input tensor, size in bytes: 602112
wasmedge: symbol lookup error: /usr/local/lib/wasmedge/libwasmedgePluginWasiNN.so: undefined symbol: _ZNK5torch3jit6Object11find_methodERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

** My hypothesis is that WasmEdge is not able to support pytorch（/tensorflow） operations on GPU or not compatible to cuda-based libtorch. **

Looking foward to your solution! Thank you!

**Comment by hydai** [comment]
Hi @q82419 and @gusye1234,

It looks like the `libtorch` provides different ABIs between the CPU one and the GPU one. Do we have any plan for the GPU one?

**Comment by gusye1234** [comment]
Hi @shenben, thanks for your detailed report.
Yes, we didn't test any CUDA version of `libtorch` for now. And didn't have the plan to support GPU in the near future.
The reason is a) we are still trying to support more backend(e.g. tensorflow and tensorflowlite), b) we believed CPU may be the primary device for the wasm runtime.
But we are(I am) open to support `libtorch` CUDA if you could offer a solid reason why it's urgent.

**Comment by shenben** [comment]
Hi @hydai and @gusye1234 

Thank you for your timely reply.

Currently, Transformer-based model or video-task ML more efficiently runs on GPU than CPU. That’s a great motivation for us to allow WASM to enable GPU on FaaS. 

Thank you for frankly pointing out that WasmEdge does not support GPU operations such that I am aware that the GPU-targeting work is meaningful. And I am willing to promote the development. 

By the way, I would really appreciate it if you could give me some hints about how to quickly construct GPU support on WasmEdge.

**Comment by gusye1234** [comment]
Hi, @shenben. Thanks for your interest.
For ML inference, WasmEdge follow the Wasi-NN protocol([link](https://github.com/WebAssembly/wasi-nn)), which consists of:
* `load`: the model weight. In PyTorch, it means loading the `.pt` torchscript file. [entry](https://github.com/WasmEdge/WasmEdge/blob/a6f734086d2bf3978feddc2b1283f484b96dab59/plugins/wasi_nn/wasinnfunc.cpp#L49)
* `init_execution`: of a model instance. In PyTorch, it means init a `torch::jit` model from the weight. [entry](https://github.com/WasmEdge/WasmEdge/blob/a6f734086d2bf3978feddc2b1283f484b96dab59/plugins/wasi_nn/wasinnfunc.cpp#L342)
* `set_input` of the model instance. [entry](https://github.com/WasmEdge/WasmEdge/blob/a6f734086d2bf3978feddc2b1283f484b96dab59/plugins/wasi_nn/wasinnfunc.cpp#L432)
* `compute` the forward process. [entry](https://github.com/WasmEdge/WasmEdge/blob/a6f734086d2bf3978feddc2b1283f484b96dab59/plugins/wasi_nn/wasinnfunc.cpp#L896)
* `get_output`. [entry](https://github.com/WasmEdge/WasmEdge/blob/a6f734086d2bf3978feddc2b1283f484b96dab59/plugins/wasi_nn/wasinnfunc.cpp#L725)

Before browsing the code, there are two great blogs talk about the Wasi-NN protocol which should give you an overview about what Wasi-NN is doing:
* [Implementing a WASI Proposal in Wasmtime: wasi-nn](https://bytecodealliance.org/articles/implementing-wasi-nn-in-wasmtime)
* [Machine Learning in WebAssembly: Using wasi-nn in Wasmtime](https://bytecodealliance.org/articles/using-wasi-nn-in-wasmtime)

The above implementation may look a little messy since it contains multiple compile flags. But for supporting PyTorch GPU, the only flag you want to care about is `WASMEDGE_PLUGIN_WASI_NN_BACKEND_TORCH `. To see where to define this flag and the torch deps, CMakeList [here](https://github.com/WasmEdge/WasmEdge/blob/a6f734086d2bf3978feddc2b1283f484b96dab59/plugins/wasi_nn/CMakeLists.txt#L55)

That's a lot to take in. If you want to be more familiar with WasmEdge Wasi-NN before any deep dive, you can check more demos in https://github.com/second-state/WasmEdge-WASINN-examples. But the demo for the transformer-based model is still vacant. So if you have a ready transformer-base demo using WasmEdge, please open a PR on this repo😄.
