### ISSUE TITLE
LFX Workspace: WasmEdge C++ SDK

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#2341]
This is the workspace of the LFX mentorship #2241 .

**Comment by Subhra264** [comment]
# Motivation
WasmEdge provides C SDK as the based library and uses this to implement other languages SDK such as Golang, Rust, Java, and Python(developing). Recently WasmEdge has received some requests for the C++ SDK.

The goal of this mentorship is to develop the C++ SDK with at least the `Basics` and `VM` implemented based on the WasmEdge C SDK.

# Schedule
- [ ] Study the SDK docs, the source code itself and figure out all the deliverables. (1 week)
- [ ] Setup and design the C++ SDK to expose well structured API and declare all the necessary classes and their member functions. (3 weeks)
- [ ] Write implementation of the classes for `Basics`. (3 weeks)
- [ ] Write implementation of classes for `VM`. (3 weeks)
- [ ] Write the C++ SDK installation guide and `Basics` documentation. (1 week)
- [ ] Write documentation for `VM`. (1 week)
- [ ] Implement the other features of C SDK such as the `Runtime`.

# Appendix
- [feat: WasmEdge C++ SDK](https://github.com/WasmEdge/WasmEdge/issues/1836)
- [WasmEdge C SDK](https://wasmedge.org/book/en/sdk/c/ref.html)
- [Wasm-Cpp-API](https://github.com/WebAssembly/wasm-c-api)

**Comment by Subhra264** [comment]
# 1st week
Mostly focused on exploring the WasmEdge source code to get an idea about how the existing C SDK uses its internal C++ APIs and exposes certain SDK functions -- https://github.com/WasmEdge/WasmEdge/tree/master/include/api/wasmedge and https://github.com/WasmEdge/WasmEdge/blob/master/lib/api/wasmedge.cpp.

Besides, I also looked through the `vm` internal APIs since it would help me design the C++ API for the `VM` section -- https://github.com/WasmEdge/WasmEdge/tree/master/lib/vm.

## Next Steps
> Setup and design the C++ SDK to expose well structured API and declare all the necessary classes and their member functions. (3 weeks)

Design the developer-friendly C++ API i.e. list down all the classes and member functions we are going to expose to the end developers. Once it is ready, I will go for committing some changes to the codebase and open a draft PR.
