### ISSUE TITLE
[Installer] Installer will install the `manylinux2014` version on `Ubuntu 22.04`

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#2595]
### Current State

When installing WasmEdge through the installer without `--dist` option, the installer will install `manylinux2014` version on `Ubuntu 22.04` platforms.

### Expected

Should install `Ubuntu 20.04` or `Ubuntu 22.04` version of WasmEdge release.

## Environment

- Hardware Architecture: x86_64
- Operating system: Ubuntu 22.04

## Steps to Reproduce

Use installer to install WasmEdge on docker image: `wasmedge/wasmedge:latest`, which is based on `Ubuntu 22.04`.

**Comment by hydai** [comment]
The necessity for two distinct Linux release assets arises due to a c++11abi issue when PyTorch (`libtorch`) is utilized.

If we want to facilitate the support of WASI-NN with PyTorch on contemporary Linux distributions, we can resort to the newer c++11abi. This version is readily available on the PyTorch website and is effortlessly integrated. However, a compatibility issue exists with its glibc version when implemented on older systems, like CentOS 7. We can still download the older c++11abi one from the PyTorch website, but the plugin will need a different build.

Regrettably, there are still several users utilizing CentOS 7. As a result, we must ensure that both manylinux2014 (tailored to general and older systems based on CentOS7) and Ubuntu 20.04 (equipped with the newer c++11abi and an updated glibc version) are maintained. The latter will be replaced by manylinux2_28 in the foreseeable future (refer to #2591).

On a more positive note, Ubuntu 22.04 is compatible with Ubuntu 20.04. As such, we can utilize Ubuntu 20.04 release assets in any version equal to or exceeding 20.04. With this in mind, our strategy will be to program the installer to automatically attempt to install Ubuntu 20.04 assets if it identifies the OS as Ubuntu and its version 20.04 or higher.

**Comment by SAtacker** [comment]
> ## Description
> ### Current State
> When installing WasmEdge through the installer without `--dist` option, the installer will install `manylinux2014` version on `Ubuntu 22.04` platforms.
> 
> ### Expected
> Should install `Ubuntu 20.04` or `Ubuntu 22.04` version of WasmEdge release.
> 
> ## Environment
> * Hardware Architecture: x86_64
> * Operating system: Ubuntu 22.04
> 
> ## Steps to Reproduce
> Use installer to install WasmEdge on docker image: `wasmedge/wasmedge:latest`, which is based on `Ubuntu 22.04`.

Can we install Ubuntu 20.04 release on Ubuntu 22.04 ?

**Comment by SAtacker** [comment]
> 

Okay, thanks, it is compatible, sorry i didn't read the last part earlier.

**Comment by hydai** [comment]
The worst moment is about to pass, and the dawn is ready to arrive.
CentOS 7 is EOL soooooooooooooon. And we will no longer have to support it anymore.
And then, we can unify to use manylinux_2_28 instead.

**Comment by SAtacker** [comment]
I am closing this one for now.
