### ISSUE TITLE
[Feature] [binding-java] Publish java to maven repository

### ISSUE THREAD

**Issue by liangyuanpeng** [WasmEdge/WasmEdge#2596]
## Motivation

It let user easy to use wasmEdge, part of java roadmap https://github.com/WasmEdge/WasmEdge/issues/2025

**Comment by sarthaksarthak9** [comment]
@liangyuanpeng could you pls give some more details regarding this issue

**Comment by Hrushi20** [comment]
@hydai I am interested in working on this issue. We need to register wasmEdge with Sonatype first https://central.sonatype.org/publish/publish-guide/ . Once our namespace is registered, we need to create PGP keys for signing. 

Then we can add it to our pipelines so that on every release, a new version is pushed to maven central.

Thank You :)

**Comment by q82419** [comment]
Replaced by the roadmap issue #3541.
