### ISSUE TITLE
Allocate failed ?

### ISSUE THREAD

**Issue by orangeC23** [WasmEdge/WasmEdge#2658]
### Test Case
The rust file is :
```
use std::fs::File;
use std::os::fd::AsRawFd;

fn main() {
    let file = File::open("Data/hello.txt").expect("Can not open.");
    let file_descriptor = file.as_raw_fd();
    println!("File descriptor {}", file_descriptor);

    unsafe{
        let p1:wasi::Fd = file_descriptor as u32; 
        let p2:wasi::Filesize = 0;
        let p3:wasi::Filesize = 200;

        println!("{:?}", wasi::fd_allocate(p1, p2, p3).unwrap());
    }
}
```

### Steps to Reproduce
1. Use `cargo build --target wasm32-wasi` to compile the rust file into WASM binaries allocate.wasm.
2. Use command `ls -al` in directory `Data`:
-rw-r--r--   1   staff  100  7  8 17:03 hello.txt
3. execute command `wasmer run --dir=Data allocate.wasm`
wasmer successfully execute the WASM binaries and use command `ls -al` in directory `Data`:
`-rw-r--r--   1 staff  200  7  8 17:05 hello.txt`
4. execute command `wasmedge --dir=Data allocate.wasm`
WasmEdge print:
```
File descriptor 1184160702
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Errno { code: 8, name: "BADF", message: "Bad file descriptor." }', src/main.rs:14:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2023-07-11 12:30:09.988] [error] execution failed: unreachable, Code: 0x89
[2023-07-11 12:30:09.988] [error]     In instruction: unreachable (0x00) , Bytecode offset: 0x00008f5d
[2023-07-11 12:30:09.988] [error]     When executing function name: "_start"
```

Thus, WasmEdge failed to allocate. However, wasmer executed successfully and allocate the size of hello.txt from 100 to 200.

**Comment by MediosZ** [comment]
Hi @orangeC23,

Can you tell us the OS and version of WasmEdge you are using?
I assume that you are using macOS by checking your log.
After reproducing your case with (macOS 12.6, WasmEdge 0.13.1, I believe **it should not work**.

The problem is when you use `File::open("Data/hello.txt")` to open the file, you will get a [read-only file](https://doc.rust-lang.org/std/fs/struct.File.html#method.open), which should not be modified.
And if you do so, you will get an error like `Errno { code: 76, name: "NOTCAPABLE", message: "Extension: Capabilities insufficient." }` which means that you don't have the **RIGHT** to modify the file.

On the other hand, you can try this:
```rust
use std::fs::OpenOptions;
use std::os::fd::AsRawFd;

fn main() {
    let file = OpenOptions::new()
        .read(true)
        .write(true) // Make the file writable
        .open("Data/hello.txt")
        .expect("can not open");
    let file_descriptor = file.as_raw_fd();
    println!("File descriptor {}", file_descriptor);

    unsafe {
        let p1: wasi::Fd = file_descriptor as u32;
        let p2: wasi::Filesize = 0;
        let p3: wasi::Filesize = 200;

        println!("{:?}", wasi::fd_allocate(p1, p2, p3).unwrap());
    }
}
```
And this just works like a charm.
```
$ cargo build --target wasm32-wasi
   Compiling t1 v0.1.0 (/Users/xxx/wasmtest/t1)
    Finished dev [unoptimized + debuginfo] target(s) in 1.12s
$ wasmedge --dir Data target/wasm32-wasi/debug/t1.wasm
File descriptor 1322011371
()
$ ll Data/hello.txt
-rw-r--r--  1 xxx  staff   200B Jul 20 00:44 Data/hello.txt
```

**Comment by orangeC23** [comment]
Thanks a lot ! Now it works.
