### ISSUE TITLE
[Windows] update community package on winget

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#2673]
## Motivation

A long time ago, several external contributors brought WasmEdge to Winget packages. However, it's no longer updated after 0.10.0. We would like to have the package updated again.

## Details

1. Figure out how to submit/update packages on the winget repo.
2. Submit a PR to provide the latest release on the winget repo.

## Appendix

* [WasmEdge on winget](https://github.com/microsoft/winget-pkgs/tree/master/manifests/w/WasmEdge/WasmEdge)

**Comment by abhinandanudupa** [comment]
I would like to work on this.

**Comment by hydai** [comment]
Sounds good. I think we can have 0.11.2 and 0.12.1. Do you have any other suggestions?

**Comment by abhinandanudupa** [comment]
The MSI package is not signed, which triggers a Windows smart screen warning. Can we get the packages signed?

**Comment by hydai** [comment]
I am not familiar with the Windows platform.
Do I need to do anything, such as applying a certification from anywhere? Or can I generate a random key to sign it?

**Comment by abhinandanudupa** [comment]
Looks like signing is a paid service:

https://www.computer.org/publications/tech-news/trends/what-is-a-code-signing-certificate

You can generate a self-sign but it is intended for development purposes and involves adding certificates to the target machine, source: https://codesigningstore.com/how-to-generate-self-signed-code-signing-certificate

And SSL seems to be one of the more cheaper options: https://www.ssl.com/certificates/code-signing/buy/ (checked DigiCert and GlobalSign, this is not an endorsement and I am not affliated with SSL.com in any way - just found them through a simple Google search)

But since even I don't know much about signing and publishing software, I won't be of much help.

**Comment by abhinandanudupa** [comment]
> Sounds good. I think we can have 0.11.2 and 0.12.1.

Done once MS accepts my PR.

**Comment by abhinandanudupa** [comment]
@hydai Can you help me with this?: https://github.com/microsoft/winget-pkgs/pull/112747#issuecomment-1645904821

**Comment by abhinandanudupa** [comment]
Shall I change `-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL` in [.github/workflows/reusable-build-on-windows.yml#L48](https://github.com/WasmEdge/WasmEdge/blob/12ec54c07c121da6796fe8e313ea6053c74b763f/.github/workflows/reusable-build-on-windows.yml#L48) to `-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded` as specified in [docs](https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html)?

**Comment by hydai** [comment]
We have to change the way of building LLVM from the source. If you change it directly with `MultiThreaded`, it will fail when linking with a self-built LLVM. To fix this, we should first use the LLVM/LLD from `choco` or anywhere instead of using our self-built one.

Related issue: https://github.com/WasmEdge/WasmEdge/pull/2475

**Comment by hydai** [comment]
Oh, I found a similar issue on neovim: https://github.com/neovim/neovim/issues/21249
How about adding the dependencies like this: https://github.com/microsoft/winget-pkgs/pull/107653/files

**Comment by abhinandanudupa** [comment]
Thank you for explaining the issue. Now I understand that external dependencies are treated differently.

**Comment by hydai** [comment]
> You can generate a self-sign but it is intended for development purposes and involves adding certificates to the target machine, source: https://codesigningstore.com/how-to-generate-self-signed-code-signing-certificate

Self-sign is unavailable because no one likes to add unknown or third-party certificates on their computer. However, let's ignore the signing issue because we don't know how to correct it.

**Comment by abhinandanudupa** [comment]
Versions: 0.13.2, 0.13.3, 0.13.4, 0.12.1 and 0.11.2 have been added to winget. Maybe we can have a GitHub Action to automate this process?

**Comment by hydai** [comment]
Thanks @abhinandanudupa 
That's awesome! It sounds like adding a workflow for this is excellent. Do you know how to do this?

**Comment by abhinandanudupa** [comment]
Will work on it.

**Comment by TBBle** [comment]
Oh, I didn't think to check here before I opened [an update request on the winget side](https://github.com/microsoft/winget-pkgs/issues/175820).

It'd be great to get 0.14.1 at least manually updated, since it fixes some basic behaviours on Windows as part of delivering the testsuite on Windows, so it should be a much better baseline than 0.14.0, until we have a GitHub workflow to automate updates.

**Comment by hydai** [comment]
Hi @TBBle 
Thanks for the information.
We had [a workflow](https://github.com/WasmEdge/WasmEdge/blob/master/.github/workflows/winget-submit.yml) for submitting the packages. However, it seems not working; I will take a look at the `winget-releaser` you mentioned to see if I can get this fixed.
