### ISSUE TITLE
Add ARM builds in official release

### ISSUE THREAD

**Issue by actly** [WasmEdge/WasmEdge#289]
Please add maynlinux1 builds for aarch64 and armv7 (32 bit interpreter only) into the release artifacts. Thank you.

**Comment by proohit** [comment]
Related: https://github.com/second-state/ssvm-napi/issues/75

It's been some time, but I've tried to manually build SSVM/WasmEdge with no luck.

**Comment by hydai** [comment]
Because the manylinux1 doesn't define the arm architecture images[1],  we don't provide the ARM build on manylinux1. However, there is a definition about `manylinux2014_aarch64`. So we will have the pre-built WasmEdge on manylinux2014 aarch64. The 32-bit environment is still pending.

[1]: https://github.com/pypa/manylinux#manylinux2014-centos-7-based

**Comment by hydai** [comment]
Hi @actly and @proohit 

Thanks for your interest on our ARM build. Currently, we provide armhf(armv7) interpreter only pre-built release. You can find the 0.8.1-armhf in release: https://github.com/WasmEdge/WasmEdge/releases/tag/0.8.1

The manylinux2014_aarch64 is still under construction. Once it’s ready, we will also add into the release artifacts. Thanks.
