### ISSUE TITLE
bug: Different behavior when executing code with the same effect

### ISSUE THREAD

**Issue by unicornt** [WasmEdge/WasmEdge#3000]
### Summary

I generated a wasm code and found that its behavior is different when using different runtimes. I also try to find out why it happened and I record my result in `Expected State` part.

[case.zip](https://github.com/WasmEdge/WasmEdge/files/13239729/report19.zip)

### Current State

Here is the output of WasmEdge, Wasmtime and Wasmer.
WasmEdge `return code 3` while other runtimes `return code 2`
![image](https://github.com/WasmEdge/WasmEdge/assets/18662046/dd7e876d-efb2-4f31-81d5-162d5301f8fc)

### Expected State

I think WasmEdge should `return 2` like Wasmtime and Wasmer.

I do some efforts to find out the cause of this difference. 

The different return code is caused by `call 0` in line 2016 of `case.wat`. `function 0` is `exit` function imported from wasi.
This means the local variable 0 is different before `line 2016`. And I figure out that this difference is caused by different data in `memory 60(= 2108&255)`.
The different data is written by `line 1815-1827`

![image](https://github.com/WasmEdge/WasmEdge/assets/18662046/57d09461-d77b-4ebe-84b1-84f619e339e8)

So I add extra `call 0`(the `exit` function) before `call 11` to check wether `function 11` will be executed. The return code will `never` be 43, which means `line 1821-1827` have the same effect with `line 1820`.
However, if I comment `line 1821-1827` and uncomment `line 1820`. The difference will no longer exist.

### Reproduction steps

```bash
Execute with interpreter mode and AOT mode will get the same difference.
```

### Components

CLI

### WasmEdge Version or Commit you used

0.13.4-106-g7d4213b3

### Operating system information

Ubuntu 20.04

### Hardware Architecture

x86_64

**Comment by dannypsnl** [comment]
exit code shouldn't be considered as a "bug" from my understanding, since they're just there to point out error for the next process. Anyway, please shrink your example, use `wasm-tools print xxx.wasm` to get readable format, reduce to minimal paste in the issue.

**Comment by unicornt** [comment]
> exit code shouldn't be considered as a "bug" from my understanding, since they're just there to point out error for the next process. Anyway, please shrink your example, use `wasm-tools print xxx.wasm` to get readable format, reduce to minimal and paste in the issue.

1. Here the exit code only serves as a `print` function. It will output the given `i32` variable.
2. **Please** read `Expected State` part where I record my effort to shrink the key part of the `case.wasm`. If you still want the **minimal** code file, I will try it.
3. The `case.wat` file in `case.zip` is the readable format of `case.wasm`.

**Comment by dannypsnl** [comment]
I understand what you mean, but standard didn't define everything, so different behavior didn't imply a bug. Also, the title here is unclear, an issue should be **actionable**, contributors will need at least a scope to search. Finally, a file over 10000 lines is indeed unhelpful, if you believe the analysis, please produce a minimal example.

**Comment by unicornt** [comment]
> I understand what you mean, but standard didn't define everything, so different behavior didn't imply a bug. Also, the title here is unclear, an issue should be **actionable**, contributors will need at least a scope to search. Finally, a file over 10000 lines is indeed unhelpful, if you believe the analysis, please produce a minimal example.

I understand that not every different behavior is a bug. Next time I will try "general issues" template instead of "bug report".
I found out that the mistake I made is missing the `drop` instruction before `call 4`. This mistake makes me consider it as a possible bug.
By the way, how can an issue be **actionable**? Could you please give me an example about it. I will be really appreciate about it.

**Comment by dannypsnl** [comment]
Thanks for update, I would define actionable can be roughly understand as
1. having a clear goal, e.g. support XXX feature, instruction XXX should do ... but ...
2. detail version of every tools in your command line, in this case, wasmtime's version might also relevant, maybe standard update or somewhat.
4. post shell code (command line) as codeblock.
5. post wasm code as codeblock, rather than picture or zip files, we can copy it to https://webassembly.github.io/wabt/demo/wat2wasm/ via a single click.

NOTE: If the code is still to long, try html tag `<details>`, as below:

<details>
hide
</details>

If it's unable to do it, the example should be minimal to under around 100 instructions so step tracing can be done fast, or any contributors will spend a few days but may has no issue there. No one can as understand as the original issuer, so the first detail report is important.

If this is in [discussion](https://github.com/WasmEdge/WasmEdge/discussions), it will no need to fit this standard.

If this issue is resolved, you can close it as well, thanks for contribution
