### ISSUE TITLE
question: plans to support other Rust libraries that require WASI functions that are not supported

### ISSUE THREAD

**Issue by font** [WasmEdge/WasmEdge#3035]
### Summary

I'm getting the following error when running a web app:

```shell
→ wasmedge --dir .:. app.wasm
Listening on http://0.0.0.0:8080/
thread 'main' panicked at src/routes.rs:5:52:
Failed to compile Tera template.: Error { kind: Io(Unsupported), source: Some(Error { kind: Unsupported, message: "operation not supported on this platform" }) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2023-11-14 14:26:07.181] [error] execution failed: unreachable, Code: 0x89
[2023-11-14 14:26:07.181] [error]     In instruction: unreachable (0x00) , Bytecode offset: 0x00a1e55f
[2023-11-14 14:26:07.181] [error]     When executing function name: "_start"
```

Here's the line containing the error:
```rust
let tera = tera::Tera::new("templates/*.html").expect("Failed to compile Tera template.");
```

I'm thinking this may be due to some Rust `std::fs::File` API that is needed by the [Tera template engine library](https://docs.rs/tera/1.18.1/tera/index.html) that is not supported by WASI. For example, a quick look through the Tera code path for `tera::Tera::new().create().load_from_glob()` reveals that it could be the [`std::fs::canonicalize` API](https://docs.rs/tera/1.18.1/src/tera/tera.rs.html#135).

I have some questions:
- Is this the correct analysis for this error? That is, when we've encountered an unsupported WASI function in a library dependency, we will receive this `operation not supported on this platform` error?
- Are there any plans to add WASI support for more Rust library dependencies to help build Wasm server-side applications with more ease?
- It does not seem like a tractable problem to have to continuously maintain forks of library dependencies so we can port them to WASI. What are the long-term thoughts, if any, for how to deal with this scalability problem? Do we eventually expect each library author to maintain support for WASI within the project itself?

**Comment by hydai** [comment]
The Tera crate is currently supported on wasm32-unknown-unknown but not on wasm32-wasi (see [Tera GitHub reference](https://github.com/Keats/tera/blob/69a76e750e357cbc36fe9c70678a0f3a85024c99/docs/playground/.travis.yml#L36)). If Tera or its dependencies lack wasm32-wasi support, it will result in the 'operation not supported on this platform' error.

Regarding WASI support for Rust libraries, prioritizing this is challenging due to the sheer number of crates. While we have forked and maintained some socket-related crates, the effort is substantial and difficult to sustain as more crates require maintenance. It's not feasible to expect each library author to support WASI. A more practical approach is for developers needing WASI compatibility to contribute towards supporting the wasm32-wasi target in these libraries.

**Comment by font** [comment]
Thanks @hydai for the response!
