### ISSUE TITLE
Maybe a failing creating directory bug?

### ISSUE THREAD

**Issue by Userzxcvbvnm** [WasmEdge/WasmEdge#3049]
### Summary

Fail to create a directory.

### Current State

Successfully get the file fd.
Error creating new directory.

### Expected State

Successfully get the file fd.
Directory 'newdir' created under 'Data/mydir'

### Reproduction steps

The test case is uploaded as createdir.wasm, it is compiled form createdir.c.
And using command 'wasmedge --dir=./Data createdir.wasm'

And createdir.wasm is uploaded as createdir_wasm.txt, createdir.c is uploaded as createdir-c.txt.

### Components

CLI

### WasmEdge Version or Commit you used

0.13.4

### Operating system information

Windows10

### Hardware Architecture

amd64

### Compiler flags and options

[createdir-c.txt](https://github.com/WasmEdge/WasmEdge/files/13449337/createdir-c.txt)
[createdir_wasm.txt](https://github.com/WasmEdge/WasmEdge/files/13449338/createdir_wasm.txt)

**Comment by LFsWang** [comment]
This is not a issue, because there is a bug in the createdir.c.

To open a directory, it need `O_DIRECTORY | O_PATH` flags for `open()`, or use `opendir()`.

Please check the document of `open` / `opendir` here

https://man7.org/linux/man-pages/man3/opendir.3.html
https://man7.org/linux/man-pages/man2/open.2.html
