### ISSUE TITLE
Fail to set file time ?

### ISSUE THREAD

**Issue by Userzxcvbvnm** [WasmEdge/WasmEdge#3052]
### Summary

The test case is uploaded as settime.wasm, it is compiled form settime.c.
It is unable to set the file time to the specified value in wasmedge.
[settime-wasm.txt](https://github.com/WasmEdge/WasmEdge/files/13450024/settime-wasm.txt)
[settime-c.txt](https://github.com/WasmEdge/WasmEdge/files/13450025/settime-c.txt)

### Current State

Successfully get the file fd.
utimensat.

### Expected State

Successfully get the file fd.
Time updated.
Last Access Time: 1633555200
Last Modification Time: 1633641600

### Reproduction steps

`wasmedge --dir=./Data settime.wasm`

### Any logs you want to share for showing the specific issue

The actual printing messager is shown in Current State.

### Components

CLI

### WasmEdge Version or Commit you used

0.13.4

### Operating system information

Windows10

### Hardware Architecture

amd64

### Compiler flags and options

The wasm file is compiled from the C file, using clang.

**Comment by LFsWang** [comment]
This is not a issue, because there is a bug in the settime.c.

The first argument of `utimensat` is not the fd of the file, it is the fd of the directory for the path if the path is relative. or use `AT_FDCWD`  to the current working directory .

Please check the document of `utimensat` here

https://man7.org/linux/man-pages/man2/utimensat.2.html
