### ISSUE TITLE
Softlink error ?

### ISSUE THREAD

**Issue by Userzxcvbvnm** [WasmEdge/WasmEdge#3077]
### Summary

WasmEdge could not successfully write content to the source file through a softlink file.

### Current State

In windows, WasmEdge failed to open the softlink file and prints:
```
Failed to open the file.
```

In linux, WasmEdge could not write content to Data/hello.txt. And WasmEdge create a new file Data/link/hello.txt and write content to Data/link/hello.txt. Maybe this is not correct.

### Expected State

In windows, WAMR could write content successfully to the source file Data/hello.txt. And this behavior could be considered as a right behavior, since Data/link/hello_softlink.txt points to Data/hello.txt.

### Reproduction steps

The test.c file is uploaded 
[test-c.txt](https://github.com/WasmEdge/WasmEdge/files/13559866/test-c.txt)

And the test.wasm file is uploaded. 
[test-wasm.txt](https://github.com/WasmEdge/WasmEdge/files/13559867/test-wasm.txt)

We create a normal file Data/hello.txt, and a softlink file Data/link/hello_softlink.txt points to Data/hello.txt
using command `wasmedge --dir=./Data test.wasm` to execute the wasm file.

### Screenshots

![DESCRIPTION](LINK.png)

### Components

CLI

### WasmEdge Version or Commit you used

0.13.4

### Operating system information

Windows10 Ubuntu 20.04

### Hardware Architecture

Windows(amd64) ubuntu20.04(x86_64)

### Compiler flags and options

using clang to compile the C file into Wasm binaries.

**Comment by TerryXhx** [comment]
Hey, @Userzxcvbvnm, could you share how you created the soft link file? Did you use the command `ln -s hello.txt link/hello_softlink.txt` within the ./Data path or a similar approach? Given that the target file is specified relatively, the resulting soft link file, Data/link/hello_softlink.txt, should point to the file Data/link/hello.txt. In the provided test C file, O_CREAT is specified, and it makes sense that Data/link/hello.txt would be created.

I conducted a test using `ln -s ../hello.txt link/hello_softlink.txt` within the ./Data path on Ubuntu 22.04, and WasmEdge worked as expected. The values specified were written to Data/hello.txt. Consequently, I don't think this issue is a bug in WasmEdge.

**Comment by hydai** [comment]
Fixed by #3370
