### ISSUE TITLE
bug: possible version mismatch in script: utils/wasi-nn/install-openvino.sh

### ISSUE THREAD

**Issue by jaykchen** [WasmEdge/WasmEdge#3183]
### Summary

if install with the script, I have error when running the container: 

```
(base) jaykchen@b550:~/projects/vino-container$ docker run -it openvino_wasm:latest 
root@503fc7a44062:/opt/intel/openvino_2023.2.0.13089# wasmedge --version
[2024-01-29 19:50:42.139] [error] loading failed: invalid path, Code: 0x20
[2024-01-29 19:50:42.139] [error]     load library failed:libopenvino_c.so.2302: cannot open shared object file: No such file or directory
[2024-01-29 19:50:42.139] [error] loading failed: invalid path, Code: 0x20
[2024-01-29 19:50:42.139] [error]     load library failed:libopenvino_c.so.2302: cannot open shared object file: No such file or directory
wasmedge version 0.13.5
```

issue could be here:
```
https://github.com/WasmEdge/WasmEdge/blob/bcfdf434c60e715e29aacfb6cff54eb36ed599c0/utils/wasi-nn/install-openvino.sh#L11
```

if change version from `openvino-2023.2.0` to `openvino-2023.0.2`, I see error gone
```
(base) jaykchen@b550:~/projects/vino-container$ docker run -it openvino_wasm:latest 
root@b34b54adbbb0:/opt/intel/openvino_2023.0.2.11065# wasmedge --version
wasmedge version 0.13.5
```

### Reproduction steps

1. Build with options '...'
2. Execute with flags '....'
3. Execute with inputs '....'
4. Get error

### Screenshots

![DESCRIPTION](LINK.png)

### Components

Others

### WasmEdge Version or Commit you used

openvino plugin

### Operating system information

ubuntu 22.04

### Hardware Architecture

amd64

**Comment by hydai** [comment]
Hi @jaykchen 
The OpenVINO plugin with 0.13.5 is using 2023.0.2; however, in the 0.14.0-unreleased, we plan to update it to 2023.2.0. That's why the script has already changed. If you want to use the 0.13.5 dependencies, please use the `install-openvino.sh` script, which is tagged in 0.13.5.

@CaptainVincent 
https://github.com/WasmEdge/WasmEdge/blob/bcfdf434c60e715e29aacfb6cff54eb36ed599c0/utils/wasi-nn/install-openvino.sh#L6

The echo string is not changed to `2023.2.0`, please fix it.
