### ISSUE TITLE
bug: wasmedge binaries missing from alpine release tarballs

### ISSUE THREAD

**Issue by TerrorJack** [WasmEdge/WasmEdge#3429]
### Summary

For instance, https://github.com/WasmEdge/WasmEdge/releases/download/0.14.0/WasmEdge-0.14.0-alpine3.16_x86_64_static.tar.gz only includes `include`/`lib` but not `bin`.

### Reproduction steps

N/A

### Screenshots

![DESCRIPTION](LINK.png)

### Components

CLI

### WasmEdge Version or Commit you used

0.14.0

### Operating system information

Linux build01 6.7.9 #1-NixOS SMP PREEMPT_DYNAMIC Wed Mar  6 14:54:01 UTC 2024 x86_64 GNU/Linux

### Hardware Architecture

x86_64

**Comment by hydai** [comment]
Hi @TerrorJack 
This is expected. The Alpine static release assets are for the runwasi project and the docker desktop, which only needs headers and libraries. That's why we don't ship the binaries together. Ref: https://github.com/WasmEdge/WasmEdge/blob/master/utils/docker/Dockerfile.alpine-static#L70
If necessary, we can create a new series of standalone release assets containing the binaries for the next release.
Please let me know for your use cases, thanks.

**Comment by TerrorJack** [comment]
I see, thanks for the clarification! I can compile my own static binaries shall the need arise.
