### ISSUE TITLE
LFX Workspace: Support WASI-NN proposal

### ISSUE THREAD

**Issue by q82419** [WasmEdge/WasmEdge#395]
This issue is for the workspace of the WASI-NN proposal supporting.

**Comment by st9540808** [comment]
Hi mentors, this is my first draft of my milestones. I will constantly update it when I learn more about WASI-NN proposal

## My Milestones

1. Study the WASI-NN proposal: 1 week
    - Study WITX specification and its relation to WASI-NN proposal
    - Bottleneck: Understand how binding works in WASI
    - Bottleneck: Understand how host function interacts with WasmEdge
2. Implement the first binding for WasmEdge: 1-2 weeks
    - Try to add my first binding for WasmEdge. It won't be in the code base but for me to understand the workflow to add bindings.
    - Could be the biggest bottleneck for me.
3. Implement WASI-NN: 5-6 weeks
    - Bottleneck: Find the proper openVINO implementation for WASI-NN

I see that [wasmtime](https://github.com/bytecodealliance/wasmtime) already implements WASI-NN using openVINO. Should we create "yet another implementation" in WasmEdge using openVINO as the backend?

I am considering using CMSIS-NN[^cmsis-nn] for the backend. Since the WasmEdge use cases include IoT devices, it makes sense when users want to run their application on ARM Cortex-M based microcontrollers with maximum resource utilization.

- Investigate memory utilization of WasmEdge
- Evaluate feasibility for CMSIS-NN binding

Also, I found out there exists arm-NN for Cortex-A processors, it can utilize Mail GPU and Ethos NPU when it is implemented by chip manufacturers in the future.

## Future work

Because I participate in the mentorship as part of my master research survey. They are something I can do in my master thesis if I choose WasmEdge as my research subject.

- Evaluate the performance of WasmEdge when using WASI-NN. Specifically, the latency of inference, number of operations per second, etc...
- Deploy an application on my STM32 board. It might be related to Wasm-C-API proposal because it needs to instantiate a VM instance after booting up the board.

## Appendices

- [How to Do Machine Learning on ARM Cortex-M Microcontrollers (in Chinese)](https://armkeil.blob.core.windows.net/developer/Files/pdf/white-paper/arm-how-to-do-machine-learning-on-arm-cortex-m-microcontrollers-tw.pdf)
- [WebAssembly/wasi-nn](https://github.com/WebAssembly/wasi-nn)
- [A beginner's guide to adding a new WASI syscall in Wasmtime](https://radu-matei.com/blog/adding-wasi-syscall)
- [CMSIS-NN: Efficient neural network kernels for Arm Cortex-M CPUs, arXiv:1801.06601](https://arxiv.org/abs/1801.06601)

**Comment by juntao** [comment]
This sounds great. I would suggest that we start from more popular frameworks first -- Eg Pytorch and ONNX and PaddlePaddle. They have large model zoos and online content to help us validate our implementations.

In your milestone #2, can you write up a tutorial for other ppl to follow after you have done your research? I am thinking about a tutorial that shows how to add a simple host function and then create a Rust API crate for the host function. To give you an example, here is a tutorial on how to add a host function via the C API (not the plug-in API you will use) and then create a JavaScript API: https://www.secondstate.io/articles/call-native-functions-from-javascript/

**Comment by q82419** [comment]
It seems great for the first half of this project.
For the NN part, we can complete the details after studying in the nearly future.
You can refer to the [Host Function Example in WasmEdge C API](https://github.com/WasmEdge/WasmEdge/blob/master/docs/c_api.md#Host-Functions) for your research.

**Comment by hydai** [comment]
The target of WASI-NN is not supporting those popular frameworks. Instead, it wants to provide an abstract layer for running AI models. OpenVINO supports multiple model format from various frameworks including TensorFlow, ONNX, etc. So I would like to have the OpenVINO support first. Then, it will to have multiple backends such as CMSIS-NN or arm-NN.

Also, I would like to know the compatibility of CMSIS-NN and arm-NN. How many frameworks do they support?

**Comment by q82419** [comment]
Workspace Week 1
* Checked the milestones and the study progress of the related works.
  * The milestones seems well for the study and implementation program.
  * It seems like you studied the NN related works and implementation for other runtimes for the availability of this project.
* Discussed the studying directions.
  * As mentioned in meeting, our main goal is the NN proposal. The frameworks are the tools to help us to complete the proposal. Therefore I suggested you to study and summarize the API for the WASI-NN proposal and the host function registration in WasmEdge first.
  * You can try to build your simple WASM program with customized host functions with WasmEdge for practicing.
  * Also, the test suites are important. The next step you should collect the test data for NN proposal.

**Comment by q82419** [comment]
Workspace Week 2

* Checked the study progress of WasmEdge host functions.
  * It seems like you have basic concepts of host functions in WasmEdge.
* Discussed the following survey progress.
  * For the WASI-NN host functions implementation, you should survey the function signatures and WASM test data first.

**Comment by q82419** [comment]
Workspace Week 3
* Checked the study progress of WASI-NN function signatures and test data.
  * It seems like we can reference the `wasmtime` test data for the host functions.
* Discussed the following implementation steps.
  * You should summarize the function signature for the ABI in the WasmEdge host functions. After then, we can start to choose the backend for implementation.

**Comment by liborui** [comment]
Hi guys! I am wondering if this support of WASI-NN proposal is undergoing, finished or abandoned?

**Comment by q82419** [comment]
> Hi guys! I am wondering if this support of WASI-NN proposal is undergoing, finished or abandoned?

Hi @liborui ,

We are now working on the WASI-NN proposal with the OpenVINO backend now.
You can refer to: 
#973
#1340 
#1414 
And we will keep updating the `proposal/wasi_nn` branch. Thanks.
