### ISSUE TITLE
[Integration] Create a WasmEdge provider for reactr 

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#557]
## Motivation

Reactr is function scheduler for WebAssembly runtimes. It provides a unified API to register GO functions into WebAssembly and to embed WebAssembly functions into a GO host app. It is used by a number of projects. We should incorporate WasmEdge into reactr as a supported runtime.

## Details

We will create a new set of `builder.go`, `wasmedge.go`, and `host_function.go` files to wrap the WasmEdge GO SDK functions in reactr. The WasmEdge integration should support LLVM AOT by default. 

https://github.com/suborbital/reactr/tree/main/rwasm/runtime/wasmtime

## Related to

https://github.com/suborbital/reactr/issues/159

**Comment by wangshishuo** [comment]
I have forked and created a [branch](https://github.com/second-state/reactr/tree/rwasm/wasmedge) to add WasmEdge runtime.

I can't create pull request now because there is an [issue](https://github.com/second-state/WasmEdge-go/issues/19) of WasmEdge so it can't pass all of the test cases.

The only failed test case is `wasmtest/rust_test.go`. I think it should has opened many go-routines to run the wasm. But WasmEdge engine will behave uncertainly in multi thread context. So if you run this test, you may get different error logs each time.

The advantage of using WasmEdge is the performance. Below is the time cost compared between Wasmer and WasmEdge running on my Docker container.

| Test case | Wasmer | WasmEdge |
| --- | ----------- | ---------- |
| assemblyscript_test.go | 95.506s | 21.334s |
| capability_test.go | 92.636s | 1.112s |
| db_test.go | 1.084s | 0.926s |
| interop_test.go | 123.543s | 91.026s |
| legacy_test.go | 111.821s | 74.461s |
| rust_test.go | - | Failed |
| swift_test.go | 168.521s | 98.059s |
| tinygo_test.go | 104.581s | 1.221s |

You will notice that in some test cases there is a huge improvement when using WasmEdge. I didn't research in-depth about this though I don't think it is normal.

My Docker container is running on my Macbook pro(AMD) and the OS is Ubuntu 20.04. The resources supplied to the Docker is 1 CPU, 6G Memory and 4G Swap.

If you would like to test by yourself, you should install [WasmEdge](https://github.com/WasmEdge/WasmEdge/blob/master/docs/install.md#quickstart) with version 0.9.0-rc.2 firstly.

**Comment by juntao** [comment]
I would also like to note that the above performance numbers were achieved in WasmEdge's interpreter mode. In the AOT mode, to be released in the 0.9.0 WasmEdge-GO SDK, WasmEdge could further its performance by 10x for computational tasks.

**Comment by hydai** [comment]
Hi @juntao 
What's the status of reactr? Do we already support it?

**Comment by juntao** [comment]
The ecosystem project has changed over time. Closing this.
