### ISSUE TITLE
How to pass String between Host and WASM?

### ISSUE THREAD

**Issue by zhenjunMa** [WasmEdge/WasmEdge#563]
I use `WasmEdge-Go` to let `WasmEdge` integrate with Go,  in my scenario, I need to pass String between Host and Wasm , I have checked the `Wasmedge-Go-Examples` project,  but did not find a solution, what documentation can I refer to?  or any code demo?

**Comment by zhenjunMa** [comment]
@q82419 
I see.
So how do you make WASM take the data (e.g a string) from Host? or wasmEdge is only designed to allow Host pass the data to WASM, and WASM is not allowed to take the initiative?

**Comment by q82419** [comment]
The WASM only support the basic types in functions, also in host functions.
Therefore we need the `malloc` function as you mentioned above to allocate a memory space in WASM.

In C program, for example, we can use `malloc` to allocate a memory:
```c
char *ptr = (char *)malloc(sizeof(char) * 10);
```
And then we can read/write the memory:
```c
ptr[0] = 'a';
ptr[1] = 'b';
ptr[2] = 'c';
printf("%c\n", ptr[1]);  // Will print `b` here.
```

In WASM, the WASM is defined as an isolated and sandboxed runtime.
Just like the experience in C, the compiler will handle the memory locations.
So we need to call the `malloc` functions to allocate the memory in WASM, and read/write the allowed segment, or the error will occurs.
For your case, you should call the `malloc` above to allocate the memory in WASM and get the memory offset:
```
res, err := vm.Execute("malloc", int32(10))
if err == nil {
  // The `res[0].(int32)` is the int32 return value of `malloc` function
  fmt.Println("Allocated with size 10 at address ", res[0].(int32))
}
```
The you can pass the address you got to retrieve data in memory or copy data into the memory in host functions.
```
func test(data interface{}, mem *wasmedge.Memory, params []interface{}) ([]interface{}, wasmedge.Result) {
  // You can get or set data in `mem` through the `wasmedge.Memory` APIs in host functions.
}
```
Unfortunately, we cannot copy a string (or the array-like data) in/out WASM, because the WASM memory cannot access to the main program memory and the WASM functions have only basic types.
Therefore we need to add the additional data into the host functions, or copy the data into memory instance before execution, such as you mentioned the MOSN did:
```
mem, err := w.GetExportsMem("memory")
binary.LittleEndian.PutUint32(mem[addr:], value)
```
It's the WASM's definition. I think all runtimes follow this.
So the trick you need to do is to call the `malloc` function to allocate and get the address, or pass data through additional data column of host functions.

Thanks.

**Comment by zhenjunMa** [comment]
@q82419 

Thanks to the patient explanation, I have modified the processing logic.

1. Use `b := make([]byte, 1)` to apply space in WASM.
2. Use `addr := &b[0]` to pass the address to HOST.
3. Use `Memory.SetData([]byte("xxxx"), uint(addr), uint(size))` to pass byte array into WASM in Host.

This avoids the logic of `malloc` in HostFunction.

**Comment by arcosx** [comment]
Do we have an example of using `BindgenFunc` in C or C++? I can not found in this doc https://wasmedge.org/book/en/embed/c/ref.html

**Comment by hydai** [comment]
> Do we have an example of using `BindgenFunc` in C or C++? I can not found in this doc https://wasmedge.org/book/en/embed/c/ref.html

C API doesn't yet support `Bindgen`. However, we welcome any contribution to this feature :-).

**Comment by Tails** [comment]
@hydai Does the Rust SDK support BIndgen? The documentation seems to have only Go examples, and the Rust SDK has no structs mentioning 'bindgen'.

**Comment by hydai** [comment]
Hi @apepkuss 
Do we have any plan to support wasm-bindgen or wasmedge-bindgen in our rust SDK?

**Comment by apepkuss** [comment]
@hydai In the aspect of Rust bindings, we don't have any plan for supporting `wasm-bindgen`. Our original idea was to support complex or custom types in Rust SDK after the WebAssembly Interface Types proposal was supported in runtime. But now I think we have to wait until the WebAssembly Component Model proposal is supported, right?

**Comment by Tails** [comment]
So then our remaining options for now are:

1. write data to Memory and read from WASM (https://wasmedge.github.io/WasmEdge/src/wasmedge_sdk/externals/memory.rs.html#174)
2. write to disk and read from WASM using Wasi/```std::fs::read_to_string()```

Does the Rust SDK support configuring WASI to read from a context directory like the Go SDK does here?

```go
func main() {
  wasmedge.SetLogErrorLevel()
  conf := wasmedge.NewConfigure(wasmedge.WASI)
  vm := wasmedge.NewVMWithConfig(conf)

  wasi := vm.GetImportModule(wasmedge.WASI)
  wasi.InitWasi(
    os.Args[1:],
    os.Environ(),
    []string{".:."},
  )

  err := vm.LoadWasmFile(os.Args[1])
  if err != nil {
    fmt.Println("failed to load wasm")
  }
...
```

**Comment by apepkuss** [comment]
@Tails Sure! We have an example that uses the low-level APIs defined in `wasmedge-sys`. For your convenience, I created a new one that uses the APIs in `wasmedge-sdk`. I'll launch a PR for merging it into WasmEdge master branch. In case that you wanna use it asap, I copy/paste the example code below:

```rust
//! This example uses `wasi_print_env.wasm`, which is generated by `wasi_print_env` project in the `bindings/rust/wasmedge-sys/examples` directory.
//!
//! To run this example, use the following command:
//! ```bash
//! cd bindings/rust
//! cargo run -p wasmedge-sdk --example wasi_print_env
//! ```

use wasmedge_sdk::{
    config::{CommonConfigOptions, ConfigBuilder, HostRegistrationConfigOptions},
    params, Vm,
};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // create a config with `wasi` option enabled
    let config = ConfigBuilder::new(CommonConfigOptions::default())
        .with_host_registration_config(HostRegistrationConfigOptions::default().wasi(true))
        .build()?;

    // create a vm
    let mut vm = Vm::new(Some(config))?;

    // set the envs and args for the wasi module
    let args = vec!["arg1", "arg2"];
    let envs = vec!["ENV1=VAL1", "ENV2=VAL2", "ENV3=VAL3"];
    let mut wasi_module = vm.wasi_module()?;
    wasi_module.initialize(Some(args), Some(envs), None);

    assert_eq!(wasi_module.exit_code(), 0);

    // load wasm module
    let wasm_file = std::path::PathBuf::from(env!("WASMEDGE_DIR"))
        .join("bindings/rust/wasmedge-sys/examples/data/wasi_print_env.wasm");

    vm.run_func_from_file(&wasm_file, "print_env", params!())?;

    Ok(())
}
```

**Comment by dannypsnl** [comment]
Seems solved, let me know if I'm wrong.
