### ISSUE TITLE
[Rust SDK] Host Function Multi-threading support

### ISSUE THREAD

**Issue by ZhangHanDong** [WasmEdge/WasmEdge#661]
The current implementation is single-threaded, the subsequent need to support multi-threaded.

#641

**Comment by apepkuss** [comment]
The issue has been fixed by

- The `Function` instance supports the ownership transferring and sharing between threads by implementing `Send` and `Sync` traits for [InnerFunc](https://github.com/WasmEdge/WasmEdge/blob/master/bindings/rust/wasmedge-sys/src/instance/function.rs#L421-L424);

- Replacing `thead_local` macro with [`lazy_static`](https://github.com/WasmEdge/WasmEdge/blob/master/bindings/rust/wasmedge-sys/src/lib.rs#L163-L174) macro.

**Comment by hydai** [comment]
@apepkuss 
Is this issue finished? If so, please close it.
