### ISSUE TITLE
Issues from running wasm file generated by emcc

### ISSUE THREAD

**Issue by chenyukang** [WasmEdge/WasmEdge#893]
## Description

We have a C program, we use `emcc` to generate to wasm file. 
When I use wasmedge to invoke it, it will produce error.

### Current State

```bash
cat@oops:~/code/emsdk/playc/quirc/tests$ wasmedge  --dir .:. qrtest.wasm 
[2021-12-10 16:41:13.864] [error] instantiation failed: unknown import, Code: 0x62
[2021-12-10 16:41:13.864] [error]     When linking module: "env" , function name: "invoke_iii"
[2021-12-10 16:41:13.864] [error]     At AST node: import description
[2021-12-10 16:41:13.864] [error]     At AST node: import section
[2021-12-10 16:41:13.864] [error]     At AST node: module
```
### Expected

At least print out the messages from C program:

```bash
cat@oops:~/code/emsdk/playc/quirc/tests$ ./qrtest
quirc test program
Copyright (C) 2010-2012 Daniel Beer <dlbeer@gmail.com>
Library version: 1.0

                                          Time (ms)       Count
  Filename                         Load    ID Total    ID   Dec
-------------------------------------------------------------------------------
```

## Environment

```bash 
Linux oops 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

wasmedge -v
wasmedge version 0.9.0

## Steps to Reproduce

Clone code from [https://github.com/chenyukang/quirc-wasm](https://github.com/chenyukang/quirc-wasm). 

Steps:
```
./run.sh 

wasmedge  --dir .:. qrtest.wasm 
```

**Comment by chenyukang** [comment]
Seems we can not open and write file with WASI?

```c
#include <inttypes.h>
#include <math.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>


int main(int argc, char **argv) {
    if (argc != 2) {
        fprintf(stderr, "Usage: %s <output-file>\n", argv[0]);
        return EXIT_FAILURE;
    }

    int num;
    FILE* fptr = fopen(argv[1], "w+");
    if (fptr == NULL) {
        fprintf(stderr, "Failed to open output file: %s\n", argv[1]);
        return EXIT_FAILURE;
    }
    printf("Enter num: ");
    scanf("%d",&num);

   fprintf(fptr,"%d",num);
   fclose(fptr);

  return 0;
}
```

Compile it to wasm:
```bash
emcc -g -Oz --llvm-lto 1 -s STANDALONE_WASM -s INITIAL_MEMORY=32MB -s MAXIMUM_MEMORY=4GB   -mmutable-globals   -mnontrapping-fptoint   -msign-ext   demo.c -o demo.wasm
```

Run with WasmEdge:

```bash
cat@oops:~/code/emsdk/playc/quirc/tests$ wasmedge --dir .:. ./demo.wasm hello.txt
Failed to open output file: hello.txt
```

Did I miss something?

**Comment by hydai** [comment]
> ### Current State
> ```shell
> cat@oops:~/code/emsdk/playc/quirc/tests$ wasmedge  --dir .:. qrtest.wasm 
> [2021-12-10 16:41:13.864] [error] instantiation failed: unknown import, Code: 0x62
> [2021-12-10 16:41:13.864] [error]     When linking module: "env" , function name: "invoke_iii"
> [2021-12-10 16:41:13.864] [error]     At AST node: import description
> [2021-12-10 16:41:13.864] [error]     At AST node: import section
> [2021-12-10 16:41:13.864] [error]     At AST node: module
> ```

For the first question, looks like emcc inserts some special functions in the `env` import module, which is not provided by wasmedge. That's why it is not worked.

> Failed to open output file: hello.txt


The second one, I am not sure if you need to enable something in emcc, but the program compiled via rust can create, read, and write file. At least the functionality is worked. I will take a look about emcc.

**Comment by hostilefork** [comment]
>     [2021-12-10 16:41:13.864] [error]     When linking module: "env" , function name: "invoke_iii"

These invoke instructions are put in automatically by Emscripten when you use setjmp()/longjmp() ([which you are using in `dbgutil.c`](https://github.com/chenyukang/quirc-wasm/blob/c43420f8239210b018641efa5278e49b02b82ace/dbgutil.c#L126))

The technique used to emulate these quirky functions works in browsers, but is not supported in WasmEdge.

Rather than setjmp/longjmp, there's a roadmap for Native WebAssembly exception handling for `try {...} catch {...}`.  Not in WasmEdge yet, but maybe something one might expect to see supported sooner rather than later.

https://emscripten.org/docs/porting/exceptions.html

**Comment by hydai** [comment]
We don't have a plan for supporting EMCC-related functions in the current stage, so I'm closing this as a wontfix issue.
And we have another issue with the exception handling proposal: #2335
