### ISSUE TITLE
Do you have any plan to support java as developing language?

### ISSUE THREAD

**Issue by amengpp** [WasmEdge/WasmEdge#897]
## Motivation
we want to run user-defined (third-party) codes safely in our SAAS server to let user to extend the SAAS the function. And the recommended language is java.

## Details
we've already attemped to use container(docker). but it's too slow to setup and also use to much resources.
we needs a light-weight sandbox to run user defined function(service).

**Comment by juntao** [comment]
Do you want to run WebAssembly functions inside your Java host app? We are working on Java SDK for WasmEdge for this purpose.

Or, do you want to compile Java programs to WebAssembly? That is not possible at this time since the JVM has not been ported to wasm -- but you could compile Java-like languages such as Kotlin to WebAssembly.

**Comment by amengpp** [comment]
I want to compile Java programs to WebAssembly.
Does any project has ported the JVM to wasm? or does WasmEdge have the plan?

**Comment by juntao** [comment]
Unfortunately, I am not aware of any current effort to port JVM to Wasm. 😰 Maybe GraalVM has a chance, but it will be a major effort.

**Comment by dannypsnl** [comment]
Due to no plan, close this issue.
