### ISSUE TITLE
[Misc] ANSI Code Support for different terminals

### ISSUE THREAD

**Issue by KernelErr** [WasmEdge/WasmEdge#991]
I once opened a PR to beautify the help output. (#944) And it's should work fine in most terminals.
However, I found that in Windows' native PowerShell and CMD, ANSI colors could not be handled. So raw text would be printed:

![image.png](https://s2.loli.net/2022/01/06/SQCjskxPwuTe7DH.png)

Only  Windows Terminal could handle it:

![image.png](https://s2.loli.net/2022/01/06/Iq1n6mrtKFE4M7G.png)

There's a document explaining how to enable color for Windows terminal: https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences?redirectedfrom=MSDN
We may write some code to enable `ENABLE_VIRTUAL_TERMINAL_PROCESSING` only for Windows. I would like to hear advice.

**Comment by hydai** [comment]
The powershell does support ASCII, however, the default value is off. We should find a way to enable it instead of using the windows only color code.

https://stackoverflow.com/questions/51680709/colored-text-output-in-powershell-console-using-ansi-vt100-codes


Adding some code to enable the setting is fine.

**Comment by hydai** [comment]
Fixed #994
